#!/bin/bash

set -e
set -o nounset

docker-compose pull
docker-compose build

docker-compose up -d db
for n in $(seq 1 10); do
  echo Creating database tables...
  if ! docker-compose run --rm app migrate; then
    echo Try $n/10 did not work. Trying again in 10 seconds...
    sleep 10
  else
    break
  fi
done
